name: Deploy to AWS VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: SSH into VM
          run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/.ssh/ssh_key
            sudo chmod 700 ~/.ssh
            sudo chmod 600 ~/.ssh/ssh_key
            ls -la ~/.ssh
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/ssh_key ubuntu@${{secrets.HOST}} "echo 'SSH connection successful'"
      