name: Deploy to AWS VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: checking out code
        run: |
            echo "Checking out code from the main branch"
            echo "${{secrets.SSH_PRIVATE_KEY}}"
            echo "${{secrets.HOST}}"
