name: Deploy to AWS VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: SSH into VM and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            export PATH=$HOME/.local/share/pnpm:$HOME/.nvm/versions/node/$(node -v)/bin:$HOME/.npm-global/bin:$PATH
            
            # Debugging: Check if pnpm and pm2 are available
            which pnpm
            which pm2
          
            cd /home/ubuntu/Drawly
            git pull origin main
            pnpm install
            # Express Server (http-server)
            cd apps/http-server
            pnpm run build
            pm2 restart http-server

            # WebSocket Server (ws-server)
            cd ../ws-server
            pnpm run build
            pm2 restart ws-server